In [1]:
import numpy as np

data = np.arange(24)
print("original array:")
print(data)

reshaped_data = data.reshape(4, 3, 2)
print("\nreshaped array (4, 3, 2):")
print(reshaped_data)

transposed_data = np.transpose(reshaped_data, (0, 2, 1))
print("\ntransposed array (4, 2, 3):")
print(transposed_data)
print("\nfinal shape:", transposed_data.shape)

original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

reshaped array (4, 3, 2):
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

transposed array (4, 2, 3):
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

final shape: (4, 2, 3)
